from pathlib import Path

START_DATE = "2017-01-01"
BACKTEST_START_DATE = "2018-01-01"
END_DATE = None

DB_URL = "postgresql://root:123456@localhost:5432/my_stock"
SCHEMA = "tushare_v2"

INIT_CASH = 500_000.0
COMMISSION_BUY = 0.0005
COMMISSION_SELL = 0.0015
MIN_COMMISSION = 5.0

FILTER_MIN_LIST_DAYS = 365
FILTER_MIN_CIRC_MV = 100_000
FILTER_MIN_AMOUNT = 30_000
LIQUIDITY_LOOKBACK = 20
EXCLUDE_CODE_PREFIXES = ("8", "688")

MARKET_FILTER_ENABLED = True
MARKET_INDEX_CODE = "000001.SH"
MARKET_INDEX_NAME = "上证指数"
MARKET_DROP_RET_5_THRESHOLD = -0.04
MARKET_DROP_DD_20_THRESHOLD = -0.08
MARKET_BEARISH_EXIT_ENABLED = True
MARKET_BEARISH_MIN_DROP = -0.007
MARKET_BEARISH_AMOUNT_LOOKBACK = 20
MARKET_BEARISH_AMOUNT_MULTIPLIER = 1.2
MARKET_BEARISH_RET_5_MAX = 0.0
LIMIT_DOWN_EXIT_ENABLED = True
RECENT_LIMIT_DOWN_LOOKBACK = 20
HOT_MONEY_RISK_ENABLED = True
HOT_MONEY_RISK_MIN_HITS = 2
HOT_MONEY_LIMIT_UP_LOOKBACK_SHORT = 20
HOT_MONEY_LIMIT_UP_LOOKBACK_MID = 63
HOT_MONEY_LIMIT_UP_20_THRESHOLD = 2
HOT_MONEY_LIMIT_UP_63_THRESHOLD = 3
HOT_MONEY_TURNOVER_LOOKBACK = 20
HOT_MONEY_TURNOVER_MA20_THRESHOLD = 10.0
HOT_MONEY_TURNOVER_MAX20_THRESHOLD = 20.0
HOT_MONEY_VOLUME_RATIO_LOOKBACK = 20
HOT_MONEY_VOLUME_RATIO_MAX20_THRESHOLD = 3.0
HOT_MONEY_LHB_LOOKBACK = 20
HOT_MONEY_LHB_COUNT20_THRESHOLD = 2

DOWNTREND_BUY_FILTER_ENABLED = True
DOWNTREND_FILTER_NAME = "accel_exhaustion_forbid_buy"
DOWNTREND_MA_WINDOW = 20
DOWNTREND_SLOPE_WINDOW = 10
DOWNTREND_RET_WINDOW = 21

BASE_POSITION_AMOUNT = 100_000.0
MAX_POSITION_AMOUNT = 200_000.0
BASE_POSITION_SLOTS = 5
MIN_HOLDINGS = 1
KEEP_TOP_N = 20
MIN_SCORE = 0.0
REBALANCE_FREQ = "M"
MAX_AVG_DISTANCE_63 = 0.18
MAX_RET_21 = 0.45
MIN_RET_63 = 0.0
RECENT_HIGH_SHORT_LOOKBACK = 21
RECENT_HIGH_LOOKBACK = 63
MAX_HIGH_POS_21 = 0.95
STRONG_TREND_ABOVE_RATIO_63 = 0.80
STRONG_TREND_ABOVE_RATIO_126 = 0.60
STRONG_TREND_RET_63 = 0.80

LONG_MAX_HOLDINGS = 5
LONG_MAX_TOTAL_EXPOSURE = 500_000.0
LONG_POSITION_STEPS = (80_000.0, 60_000.0, 40_000.0, 20_000.0, 50_000.0)
LONG_PULLBACK_LOOKBACK = 63
LONG_PULLBACK_THRESHOLD = -0.05
LONG_STRONG_TREND_PULLBACK_THRESHOLD = -0.03
LONG_STOP_LOSS_PCT = -0.05
LONG_ADD_PROFIT_THRESHOLDS = (0.05, 0.10, 0.15, 0.50)
BULL_ADD_PROFIT_THRESHOLDS = (0.045, 0.09, 0.135, 0.42)
RANK_STALE_EXIT_ENABLED = True
RANK_STALE_EXIT_MIN_TRADING_DAYS = 231
RANK_STALE_EXIT_PROFIT_THRESHOLD_PCT = 0.0
PURE_BULL_EXTRA_TOTAL_CAP = 1_200_000.0
PURE_BULL_EXTRA_NAV_RATIO = 0.60
LONG_BEARISH_DROP_THRESHOLD = -0.07
LONG_BEARISH_AMOUNT_MULTIPLIER = 1.5
LONG_BEARISH_CLOSE_LOW_POSITION = 0.25

MARKET_REGIME_FILTER_ENABLED = True
BULL_EARLY_ENTRY_PULLBACK_THRESHOLD = -0.025
BULL_EARLY_ENTRY_STRONG_PULLBACK_THRESHOLD = -0.012
REGIME_NEUTRAL_PULLBACK_THRESHOLD = -0.07
REGIME_STRONG_TREND_PULLBACK_THRESHOLD = -0.026
REGIME_BEAR_EXIT_LOSS_THRESHOLD = 0.0
REGIME_BEAR_BREADTH_THRESHOLD = 0.45
REGIME_BULL_BREADTH_THRESHOLD = 0.55
REGIME_BEAR_DD_252_THRESHOLD = -0.20
REGIME_BULL_DD_252_THRESHOLD = -0.10

BEAR_PROBE_BUY_ENABLED = True
BEAR_PROBE_POSITION_FRACTION = 0.15
BEAR_PROBE_MAX_TOTAL_EXPOSURE = 75_000.0
BEAR_PROBE_MIN_BREADTH = 0.35
BEAR_PROBE_BREADTH_IMPROVE_5 = 0.08
BEAR_PROBE_BBI_SLOPE_WINDOW = 5

DC_SEGMENT_OVERLAY_ENABLED = True
DC_SEGMENT_OVERLAY_ACTIVE_FROM = "2025-01-02"
DC_SEGMENT_MEMBER_LAG_DAYS = 1
DC_SEGMENT_CRASH_RET_20 = -0.10
DC_SEGMENT_CRASH_DD_20 = -0.15

LOOKBACK_SHORT = 21
LOOKBACK_MID = 63
LOOKBACK_LONG = 126
MIN_HISTORY_ROWS = 160

OUTPUT_DIR = Path(__file__).parent / "output"
PANEL_PATH = OUTPUT_DIR / "panel.parquet"
MARKET_INDEX_PATH = OUTPUT_DIR / "market_index.parquet"
STOCK_LIST_PATH = OUTPUT_DIR / "stock_list.csv"
SCORES_PATH = OUTPUT_DIR / "strength_scores.csv"
REBALANCE_LOG_PATH = OUTPUT_DIR / "rebalance_log.csv"
TRADE_RECORDS_PATH = OUTPUT_DIR / "trade_records.csv"
NAV_SERIES_PATH = OUTPUT_DIR / "nav_series.csv"
SUMMARY_PATH = OUTPUT_DIR / "summary.json"
COMPARE_V1_PATH = OUTPUT_DIR / "compare_v1.csv"
REPORT_PATH = OUTPUT_DIR / "report.html"
LAST_HOLDINGS_PATH = OUTPUT_DIR / "last_holdings.json"

V1_STATS_PATH = Path(__file__).parent.parent / "v1" / "output" / "stats_summary.csv"
